# W&B settings
wandb:
  project: "tabular-reconstruction-attacks"
  name: "PoPETs report"
  group: "<Attack_type>"
  tags:
    - "chained"
    - "development"

# Dataset settings
dataset:
  name: "nist_arizona_data"
  size: 10_000
  dir: "/Users/stevengolob/Documents/school/PhD/"
QI: "QI1"

# Synthetic data generation
sdg_method: "MST"
sdg_params:
  eps: 10
  bins: 20

# RePaint attack parameters
attack_method: "TabDDPM+RePaint"
attack_params:
#  method_ref: "partial_tabddpm_reconstruction"
  method_ref: "repaint_reconstruction"

  # repaint params
  num_epochs: 100_000
  resamples: 5
  jump: 10
  num_timesteps: 1000
  hidden_dims:
    - 512
    - 1024
    - 1024
    - 1024
    - 512
  dropout: 0.1
  jump_fn: "jump_max10" # or "jump_threeQuarter"

  # linear model (regression) params
  degree: 2
  epsilon: 1.35
  alpha: 1.0
  alpha_sdg: 0.0001
  l1_ratio: 0.5
  penalty: 'l2'
  max_iter: 100 # 1000 for 'sdg_regressor'
  knn_k: 5
  knn_use_weights: True

  # MLP params
  test_size: 0.2
  hidden_dims:
    - 128
    - 96
    - 64
  batch_size: 264
  learning_rate: 0.0003
  epochs: 250
  patience: 200
  dropout_rate: 0.2

  # RF params
  max_depth: 25
  num_estimators: 25




# Other experiment settings
random_seed: 42